### ISSUE TITLE
arduino IDE does not start with these tools giving PApplet not found

### ISSUE THREAD

**Issue by agnunez** [davidvondle/Upload-And-Retrieve-Source#4]
Using latest version of arduino-nightly (beyond 1.6.x) in linux (ubuntu 14.04) and these repo installed in tools subdirectory, arduino start with logo giving this error after some time:

java.lang.NoClassDefFoundError: processing/core/PApplet
    at template.tool.GistUploader.save(Unknown Source)
    at template.tool.GistUploader.init(Unknown Source)
    at processing.app.Editor.addTools(Editor.java:894)
    at processing.app.Editor.buildToolsMenu(Editor.java:747)
    at processing.app.Editor.buildMenuBar(Editor.java:526)
    at processing.app.Editor.<init>(Editor.java:216)
    at processing.app.Base.handleOpen(Base.java:936)
    at processing.app.Base.handleOpen(Base.java:901)
    at processing.app.Base.handleNew(Base.java:792)
    at processing.app.Base.<init>(Base.java:487)
    at processing.app.Base.guardedMain(Base.java:225)
    at processing.app.Base.main(Base.java:136)
    at ArduinoIDE.main(ArduinoIDE.java:42)
Caused by: java.lang.ClassNotFoundException: processing.core.PApplet
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 13 more

**Comment by davidvondle** [comment]
There was a redesign of which classes functionality lives in arduino-core.  The new version will have fixed this.
